spring:
  application:
    name: blog-service-test
  
  # Testcontainers will provide the datasource configuration
  # The actual connection details will be injected by Testcontainers
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Disable email sending in tests
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    test-connection: false

  # Disable Docker Compose for tests
  docker:
    compose:
      enabled: false

# JWT Configuration for tests
jwt:
  secret: testSecretKeyForTestingPurposesOnlyThisShouldBeAtLeast256BitsLong
  expiration: 86400000 # 24 hours in milliseconds

# Magic Link Configuration for tests
app:
  magic-link:
    base-url: http://localhost:3000
    expiration-minutes: 15

# Disable Redis for tests (use in-memory cache)
spring:
  cache:
    type: simple 