# Production Configuration
spring:
  profiles:
    active: prod
  
  # Database Configuration for Production
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  # JPA Configuration for Production
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
  
  # Redis Configuration for Production
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 2
          max-wait: 10000ms
  
  # Cache Configuration for Production
  cache:
    type: redis
    redis:
      time-to-live: 900000 # 15 minutes
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "blogapp:prod:"

# JWT Configuration for Production
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours

# Application Configuration for Production
app:
  magic-link:
    base-url: ${MAGIC_LINK_BASE_URL}
    expiration-minutes: ${MAGIC_LINK_EXPIRATION_MINUTES:10}
  
  email-service:
    base-url: ${EMAIL_SERVICE_BASE_URL}
  
  cache:
    user:
      ttl: 600000 # 10 minutes
      max-size: 2000
    post:
      ttl: 900000 # 15 minutes
      max-size: 1000
    clap:
      ttl: 600000 # 10 minutes
      max-size: 5000

# Actuator Configuration for Production
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: false
    java:
      enabled: false
    os:
      enabled: false

# Logging Configuration for Production
logging:
  level:
    com.codehacks: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/blogapp.log
    max-size: 100MB
    max-history: 30

# Server Configuration for Production
server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain
  http2:
    enabled: true
  tomcat:
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 20000
    max-connections: 8192
    accept-count: 100 