apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-backend-deployment
  labels:
    app: blogapp-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogapp-backend
  template:
    metadata:
      labels:
        app: blogapp-backend
    spec:
      imagePullSecrets:
        - name: my-docker-credentials
      containers:
        - name: blogapp-backend-container
          image: blogapp-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://blogapp-postgresql:5432/blogapp
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
