apiVersion: v1
kind: Service
metadata:
  name: blogapp-backend-service
  labels:
    app: blogapp-backend
spec:
  selector:
    app: blogapp-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP