apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogapp-frontend-deployment
  labels:
    app: blogapp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogapp-frontend
  template:
    metadata:
      labels:
        app: blogapp-frontend
    spec:
      imagePullSecrets:
        - name: my-docker-credentials
      containers:
        - name: blogapp-frontend-container
          image: docker.io/rume7/blogapp-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: "http://blogapp-backend-service:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
