apiVersion: v1
kind: Service
metadata:
  name: blogapp-frontend-service
  labels:
    app: blogapp-frontend
spec:
  selector:
    app: blogapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer